package herta;

import herta.command.Command;
import herta.exception.HertaException;
import herta.parser.CommandType;
import herta.parser.Parser;
import herta.storage.Storage;
import herta.task.TaskList;
import herta.ui.ResponseCollector;
import herta.ui.Ui;
import herta.ui.UiOutput;

/**
 * Provides the command-line entry point for the Herta task manager.
 */
public class Herta {
    private final Ui ui;
    private final Storage storage;
    private final Parser parser;
    private final TaskList tasks;
    private final String loadingError;

    /**
     * Creates a Herta instance backed by the specified data file.
     *
     * @param filePath the path of Herta's data file
     */
    public Herta(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);
        parser = new Parser();

        TaskList loadedTasks;
        String loadError = null;
        try {
            loadedTasks = storage.load();
        } catch (HertaException e) {
            loadedTasks = new TaskList();
            loadError = e.getMessage();
        }
        tasks = loadedTasks;
        loadingError = loadError;
    }

    /**
     * Starts Herta and processes commands entered by the user.
     */
    public void run() {
        ui.showWelcome();

        if (loadingError != null) {
            ui.showMessage(loadingError);
            ui.close();
            return;
        }

        boolean shouldExit = false;
        while (!shouldExit) {
            String input = ui.readCommand();
            if (input == null) {
                ui.showSeparator();
                ui.showGoodbye();
                break;
            }
            ui.showSeparator();

            ResponseCategory responseCategory = processCommand(input, ui);
            shouldExit = responseCategory == ResponseCategory.EXIT;

            if (!shouldExit) {
                ui.showSeparator();
            }
        }

        ui.close();
    }

    /**
     * Parses and executes one command using the supplied output interface.
     *
     * @param input the command to process
     * @param output the output interface used to display responses
     * @return the semantic category of the processed command response
     */
    private ResponseCategory processCommand(String input, UiOutput output) {
        CommandType commandType = parser.parseCommandType(input);
        try {
            Command command = parser.parse(input, commandType);
            command.execute(tasks, output, storage);
            return ResponseCategory.fromCommandType(commandType);
        } catch (HertaException e) {
            output.showMessage(e.getMessage());
            return ResponseCategory.ERROR;
        }
    }

    /**
     * Launches Herta using its default data file.
     *
     * @param args command-line arguments, which are not used
     */
    public static void main(String[] args) {
        new Herta("data/herta.txt").run();
    }

    /**
     * Processes one command and returns the response for a graphical user interface.
     *
     * @param input the command entered by the user
     * @return the response message and exit status generated by the command
     */
    public HertaResponse getResponse(String input) {
        ResponseCollector response = new ResponseCollector();
        ResponseCategory responseCategory = processCommand(input, response);
        boolean exitRequested = responseCategory == ResponseCategory.EXIT;
        return new HertaResponse(response.getOutput(), exitRequested, responseCategory);
    }
}
