package herta;

import herta.command.Command;
import herta.exception.HertaException;
import herta.exception.UsageGuidanceException;
import herta.parser.CommandType;
import herta.parser.Parser;
import herta.storage.Storage;
import herta.storage.TaskRepository;
import herta.task.TaskList;
import herta.ui.ResponseCollector;
import herta.ui.Ui;
import herta.ui.UiOutput;

/**
 * Provides the command-line entry point for the Herta task manager.
 */
public class Herta {
    private static final String DEFAULT_DATA_FILE = "data/herta.txt";

    private final Ui ui;
    private final Parser parser;
    private final TaskRepository repository;
    private final String loadingError;

    /**
     * Creates a Herta instance backed by the default data file.
     */
    public Herta() {
        this(DEFAULT_DATA_FILE);
    }

    /**
     * Creates a Herta instance backed by the specified data file.
     *
     * @param filePath the path of Herta's data file
     */
    public Herta(String filePath) {
        ui = new Ui();
        parser = new Parser();

        TaskRepository loadedRepository;
        String loadError;
        try {
            loadedRepository = TaskRepository.load(filePath);
            loadError = null;
        } catch (HertaException e) {
            Storage activeStorage = new Storage(filePath);
            Storage archiveStorage = new Storage(Storage.resolveArchivePath(filePath).toString());
            loadedRepository = new TaskRepository(activeStorage, archiveStorage,
                    new TaskList(), new TaskList());
            loadError = e.getMessage();
        }
        repository = loadedRepository;
        loadingError = loadError;
    }

    /**
     * Starts Herta and processes commands entered by the user.
     */
    public void run() {
        ui.showWelcome();

        try {
            if (loadingError != null) {
                ui.showMessage(loadingError);
                return;
            }
            runCommandLoop();
        } finally {
            ui.close();
        }
    }

    /**
     * Reads and processes commands until the user exits or input reaches EOF.
     */
    private void runCommandLoop() {
        while (true) {
            String input = ui.readCommand();
            if (input == null) {
                ui.showSeparator();
                ui.showGoodbye();
                return;
            }
            ui.showSeparator();

            ResponseCategory responseCategory = processCommand(input, ui);
            if (responseCategory == ResponseCategory.EXIT) {
                return;
            }
            ui.showSeparator();
        }
    }

    /**
     * Parses and executes one command using the supplied output interface.
     *
     * @param input the command to process
     * @param output the output interface used to display responses
     * @return the semantic category of the processed command response
     */
    private ResponseCategory processCommand(String input, UiOutput output) {
        if (!isReady()) {
            output.showMessage(loadingError);
            return ResponseCategory.ERROR;
        }
        CommandType commandType = parser.parseCommandType(input);
        Command command;
        try {
            command = parser.parse(input, commandType);
        } catch (HertaException e) {
            output.showMessage(e.getMessage());
            return ResponseCategory.USAGE_GUIDANCE;
        }

        try {
            command.execute(repository, output);
            return ResponseCategory.fromCommandType(commandType);
        } catch (UsageGuidanceException e) {
            output.showMessage(e.getMessage());
            return ResponseCategory.USAGE_GUIDANCE;
        } catch (HertaException e) {
            output.showMessage(e.getMessage());
            return ResponseCategory.ERROR;
        }
    }

    /**
     * Launches Herta using its default data file.
     *
     * @param args command-line arguments, which are not used
     */
    public static void main(String[] args) {
        new Herta().run();
    }

    /**
     * Processes one command and returns the response for a graphical user interface.
     *
     * @param input the command entered by the user
     * @return the response message and exit status generated by the command
     */
    public HertaResponse getResponse(String input) {
        ResponseCollector responseCollector = new ResponseCollector();
        ResponseCategory responseCategory = processCommand(input, responseCollector);
        boolean isExitRequested = responseCategory == ResponseCategory.EXIT;
        return new HertaResponse(responseCollector.getOutput(), isExitRequested, responseCategory);
    }

    /**
     * Indicates whether startup completed successfully and commands may be processed.
     *
     * @return {@code true} when both task collections are ready
     */
    public boolean isReady() {
        return loadingError == null;
    }

    /**
     * Returns the startup error, if startup failed.
     *
     * @return the startup error or {@code null} when Herta is ready
     */
    public String getLoadingError() {
        return loadingError;
    }
}
